name: Actions 😎

on: push
jobs:
  build:
    name: Build my project ✨
    runs-on: windows-2019
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: LINKa.plays
          targetPlatform: StandaloneWindows

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build/StandaloneWindows
  installer:
    name: Create installer
    runs-on: windows-2019
    needs: build
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: mkdir build
      - run: curl.exe --output build/launcher.zip --url https://linka.su/linkaplay/launcher.zip
      - uses: actions/download-artifact@v2
        with:
          name: Build
          path: build/LINKa.plays
      - run: powershell -command "Expand-Archive -Force 'build/launcher.zip' 'build/'"
      - run: cp 'build/launcher/*' 'build/LINKa.plays/'
      - run: dir 'build/LINKa.plays/'
      - name: Building the installer
        run: |
          node version.js
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "installer.iss"
        shell: cmd
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: build/linka.plays.setup.exe
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: installer
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: mkdir build
      - run: mkdir build/linka.plays
      - run: node version.js
      - uses: actions/download-artifact@v2
        with:
          name: Installer
          path: build/
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - name: Deploy to server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}      
        run: |
          cat build/linka.plays.setup.exe | ssh -i ~/.ssh/key -o StrictHostKeyChecking=no aacidov@linka.su dd of=/var/www/wordpress/linkaplay/linkaplaysetup.exe
          cat ./build/linka.plays/version.json | ssh -i ~/.ssh/key -o StrictHostKeyChecking=no aacidov@linka.su dd of=/var/www/wordpress/linkaplay/version.json
